const mongoose=require("mongoose")
const ResumeSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    title:{
     type:String,
     required:true
    },
    thumbnailLink:{
        type:String,
    },
    template:{
        type:String,
        ColorPalette:[String]
    },
    profileInfo:{
        profilePreviewUrl:String,
        fullName:String,
        designation:String,
        summary:String
    },
    contactInfo:{
        email:String,
        phone:String,
        location:String,
        linkedin:String,
        github:String,
        website:String
    },

    workExperience:[{
        company:String,
        role:String,
        stratDate:String,
        endDate:String,
        description:String
    }],
  education:[
    {
        degree:String,
        institution:String,
        stratDate:String,
        endDate:String,
    }
  ],
  skills:[{
name:String,
progress:Number
  }],
   projects:[
    {
        title:String,
        description:String,
        githublink:String,
        liveDemo:String,
    }
   ],
   certification:[{
    title:String,
    issuer:String,
    year:String
   }],
   languages:[{
    name:String,
    progress:Number
   }],
   interests:[String]
}
{
    timestamps:{createdAt:"createdAt",updatedAt:"updatedAt",}
}
)

exports 