const mongoose=require("mongoose")
const ResumeSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    title:{
     type:String,
     required:true
    },
    thumbnailLink:{
        type:String,
    },
    template:{
        type:String,
        ColorPalette:[String]
    },
    profileInfo:{
        profilePreviewUrl:String,
        fullName:String,
        designation:String,
        summary:String
    },
    contactInfo:{
        email:String,
        phone:String,
        location:String,
        linkedin:String,
        github:String,
        website:String
    },

    workExperience:{
        company:String,
        role:String,
        stratdate
    }
})